"""empty message

Revision ID: 1f5beb8fe126
Revises: 7179ff716c77
Create Date: 2022-04-18 14:28:51.150154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5beb8fe126'
down_revision = '7179ff716c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('answer', sa.Column('page_summary', sa.Text(), nullable=True))
    op.add_column('answer', sa.Column('mail_response', sa.Text(), nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.drop_column('answer', 'answer')
    op.drop_column('answer', 'main')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('answer', sa.Column('main', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('answer', 'mail_response')
    op.drop_column('answer', 'page_summary')
    op.drop_column('answer', 'question')
    # ### end Alembic commands ###
