"""empty message

Revision ID: 20831580d15b
Revises: 635ad28521f8
Create Date: 2022-04-27 01:10:13.124755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20831580d15b'
down_revision = '635ad28521f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
