"""empty message

Revision ID: 635ad28521f8
Revises: fa1f174ed0be
Create Date: 2022-04-20 22:54:53.766033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635ad28521f8'
down_revision = 'fa1f174ed0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('answer', sa.Column('page_summary', sa.Text(), nullable=True))
    op.add_column('answer', sa.Column('mail_response', sa.Text(), nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.drop_column('answer', 'main')
    op.drop_column('answer', 'answer')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.add_column('parent', sa.Column('select', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'select')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('answer', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('main', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('answer', 'mail_response')
    op.drop_column('answer', 'page_summary')
    op.drop_column('answer', 'question')
    # ### end Alembic commands ###
