"""empty message

Revision ID: 9a2180776b40
Revises: 8e65aec74e81
Create Date: 2022-04-17 17:37:32.560113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2180776b40'
down_revision = '8e65aec74e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.add_column('parent', sa.Column('select', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'select')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
