"""empty message

Revision ID: b5e0eddf984c
Revises: 20831580d15b
Create Date: 2022-04-27 01:13:55.202512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e0eddf984c'
down_revision = '20831580d15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('response', sa.Text(), nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.drop_column('answer', 'mail_response')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('answer', sa.Column('mail_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('answer', 'response')
    # ### end Alembic commands ###
