"""empty message

Revision ID: c8b1dcc8c858
Revises: f58d327445c0
Create Date: 2022-04-12 01:52:32.259390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b1dcc8c858'
down_revision = 'f58d327445c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('page_summary', sa.Text(), nullable=True),
    sa.Column('mail_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('select', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heading_child1',
    sa.Column('child1_id', sa.Integer(), nullable=False),
    sa.Column('heading_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child1_id'], ['child1.id'], ),
    sa.ForeignKeyConstraint(['heading_id'], ['heading.id'], ),
    sa.PrimaryKeyConstraint('child1_id', 'heading_id')
    )
    op.create_table('parent_heading',
    sa.Column('heading_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['heading_id'], ['heading.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('heading_id', 'parent_id')
    )
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('parent_heading')
    op.drop_table('heading_child1')
    op.drop_table('parent')
    op.drop_table('heading')
    op.drop_table('child1')
    # ### end Alembic commands ###
