"""empty message

Revision ID: d0a6bbb279ea
Revises: 84fee61498af
Create Date: 2022-04-12 02:10:40.668037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a6bbb279ea'
down_revision = '84fee61498af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch2', 'branch1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch1', 'tree_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer', 'branch2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
