"""empty message

Revision ID: edfc09b6a13e
Revises: 8d782c25ff26
Create Date: 2022-04-12 01:01:11.897408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfc09b6a13e'
down_revision = '8d782c25ff26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_heading',
    sa.Column('heading_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['heading_id'], ['heading.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('heading_id', 'parent_id')
    )
    op.add_column('child1', sa.Column('page_summary', sa.Text(), nullable=True))
    op.add_column('child1', sa.Column('mail_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child1', 'mail_response')
    op.drop_column('child1', 'page_summary')
    op.drop_table('parent_heading')
    # ### end Alembic commands ###
